// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motorcycle.Models;

#nullable disable

namespace Motorcycle.Migrations
{
    [DbContext(typeof(MotorcycleDbContext))]
    [Migration("20260712145238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Motorcycle.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Brands__3214EC07B6067D07");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Motorcycle.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07170F2FE1");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex(new[] { "Name" }, "UQ__Categori__737584F6F38BA0B3")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Motorcycle.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Dealers__3214EC071D7D9898");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("Motorcycle.Models.Motorcycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineCc")
                        .HasColumnType("int")
                        .HasColumnName("EngineCC");

                    b.Property<decimal?>("FuelTankCapacity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LaunchYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("Mileage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TopSpeed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Motorcyc__3214EC07E5A379FB");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Motorcycles");
                });

            modelBuilder.Entity("Motorcycle.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3214EC07E31AA9CD");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Motorcycle.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07FC2E4B2C");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F67B6471D0")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Motorcycle.Models.TestRideBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MotorcycleId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TestRide__3214EC0717D26238");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("TestRideBookings");
                });

            modelBuilder.Entity("Motorcycle.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC076ECD74A9");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534E75D6996")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Motorcycle.Models.Brand", b =>
                {
                    b.HasOne("Motorcycle.Models.User", "CreatedByUser")
                        .WithMany("BrandCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Brands_CreatedBy");

                    b.HasOne("Motorcycle.Models.User", "UpdatedByUser")
                        .WithMany("BrandUpdatedByUsers")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_Brands_UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Motorcycle.Models.Category", b =>
                {
                    b.HasOne("Motorcycle.Models.User", "CreatedByUser")
                        .WithMany("CategoryCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Categories_CreatedBy");

                    b.HasOne("Motorcycle.Models.User", "UpdatedByUser")
                        .WithMany("CategoryUpdatedByUsers")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_Categories_UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Motorcycle.Models.Dealer", b =>
                {
                    b.HasOne("Motorcycle.Models.User", "CreatedByUser")
                        .WithMany("DealerCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Dealers_CreatedBy");

                    b.HasOne("Motorcycle.Models.User", "UpdatedByUser")
                        .WithMany("DealerUpdatedByUsers")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_Dealers_UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Motorcycle.Models.Motorcycle", b =>
                {
                    b.HasOne("Motorcycle.Models.Brand", "Brand")
                        .WithMany("Motorcycles")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_Motorcycles_Brands");

                    b.HasOne("Motorcycle.Models.Category", "Category")
                        .WithMany("Motorcycles")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Motorcycles_Categories");

                    b.HasOne("Motorcycle.Models.User", "CreatedByUser")
                        .WithMany("MotorcycleCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_Motorcycles_CreatedBy");

                    b.HasOne("Motorcycle.Models.User", "UpdatedByUser")
                        .WithMany("MotorcycleUpdatedByUsers")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_Motorcycles_UpdatedBy");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Motorcycle.Models.RefreshToken", b =>
                {
                    b.HasOne("Motorcycle.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Motorcycle.Models.TestRideBooking", b =>
                {
                    b.HasOne("Motorcycle.Models.User", "CreatedByUser")
                        .WithMany("TestRideBookingCreatedByUsers")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK_TestRideBookings_CreatedBy");

                    b.HasOne("Motorcycle.Models.Motorcycle", "Motorcycle")
                        .WithMany("TestRideBookings")
                        .HasForeignKey("MotorcycleId")
                        .IsRequired()
                        .HasConstraintName("FK_TestRideBookings_Motorcycles");

                    b.HasOne("Motorcycle.Models.User", "UpdatedByUser")
                        .WithMany("TestRideBookingUpdatedByUsers")
                        .HasForeignKey("UpdatedByUserId")
                        .HasConstraintName("FK_TestRideBookings_UpdatedBy");

                    b.HasOne("Motorcycle.Models.User", "User")
                        .WithMany("TestRideBookingUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TestRideBookings_Users");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Motorcycle");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Motorcycle.Models.User", b =>
                {
                    b.HasOne("Motorcycle.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Motorcycle.Models.Brand", b =>
                {
                    b.Navigation("Motorcycles");
                });

            modelBuilder.Entity("Motorcycle.Models.Category", b =>
                {
                    b.Navigation("Motorcycles");
                });

            modelBuilder.Entity("Motorcycle.Models.Motorcycle", b =>
                {
                    b.Navigation("TestRideBookings");
                });

            modelBuilder.Entity("Motorcycle.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Motorcycle.Models.User", b =>
                {
                    b.Navigation("BrandCreatedByUsers");

                    b.Navigation("BrandUpdatedByUsers");

                    b.Navigation("CategoryCreatedByUsers");

                    b.Navigation("CategoryUpdatedByUsers");

                    b.Navigation("DealerCreatedByUsers");

                    b.Navigation("DealerUpdatedByUsers");

                    b.Navigation("MotorcycleCreatedByUsers");

                    b.Navigation("MotorcycleUpdatedByUsers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TestRideBookingCreatedByUsers");

                    b.Navigation("TestRideBookingUpdatedByUsers");

                    b.Navigation("TestRideBookingUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
